name: Test for CLI tools

permissions:
  contents: read

on:
  push:
    branches: [main, "support-*"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USI_ENGINE_JSON: .config/electron-shogi/usi_engine.json
    steps:
      # Setup
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm version
      - run: npm ci --no-audit --no-fund

      # usi-csa-bridge
      - run: npm run usi-csa-bridge:build
      - name: Test usi-csa-bridge (Scenario 1)
        timeout-minutes: 1
        run: ./src/tests/e2e/usi-csa-bridge/run 1

      # Electron App
      - run: npm run electron:build
      - name: Test --add-engine command
        timeout-minutes: 1
        run: |
          xvfb-run -a ./dist/linux-unpacked/electron-shogi \
            --no-sandbox \
            --add-engine \
            ./scripts/dummy-usi-engine "Dummy Engine" \
            10 \
            H4sIAAAAAAAAE42Sa0+DMBSG/8v53IXLLjpiTCxx0W+axU/GmALd1ggtgWI2F/67KRY4u+FCApyXvs/bHs4eynjDMwYB8DJwnKoUIy7XQvKRyrVQshzFqcgjxYpklDDNgID9AMEelroQcv1gXiXLOASdQkDvciOUjWBsRcILCDzXJZDwFatSDQGslAIC3yytzOKEmQtqYjn0hEyHyF5Pipi5elJ4QgqHSD7e4x3Pcr27R/tslZrAQqTccHETeq2LWFkJh4wvN8LJmd44WjnGh2PomRg6HDNB9vCMPRy2T69uRbjh8RfugxU6fGxqzJ5hti4qjsBN2VLpMZUOUG/MX8+FPJjLpu7/eC4kttyijXgugUxICMyTbe3I2m15UwunR3B6GT7v3K45j8oiddClP6E/j6mR32vSixKCd1g0U0JZ0dx/gMBrtW3u1RY+cDcXB/Nk1rbZ9DibDmR712bXBGiltZKIboWOHrV1h/drAm/L588nVm6QsZMu9RSddOx3x5y485kFvijZrDxAWvHS5Pj/TmNNgEsWpfyRFemuzVixtOT1LzpIE4pLBQAA
          test "$(cat $HOME/$USI_ENGINE_JSON | jq -r '.engines[].name')" = "Dummy Engine"
          test "$(cat $HOME/$USI_ENGINE_JSON | jq -r '.engines[].options.FilenameA.value')" = "/path/to/file"
